# Generated by Django 5.0.1 on 2026-02-17 03:07

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMoneyTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money'), ('MTN_MOMO', 'MTN Mobile Money'), ('MOOV_MONEY', 'Moov Money'), ('FREE_MONEY', 'Free Money')], max_length=50, verbose_name='provider')),
                ('provider_transaction_id', models.CharField(blank=True, max_length=255, unique=True, verbose_name='provider transaction ID')),
                ('sender_phone_number', models.CharField(max_length=20, verbose_name='sender phone number')),
                ('sender_name', models.CharField(blank=True, max_length=255, verbose_name='sender name')),
                ('sender_country', models.CharField(max_length=3, verbose_name='sender country')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount')),
                ('currency', models.CharField(max_length=3, verbose_name='currency')),
                ('payment_method', models.CharField(default='MOBILE_MONEY', max_length=50, verbose_name='payment method')),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='INITIATED', max_length=20, verbose_name='status')),
                ('qr_code_reference', models.CharField(blank=True, max_length=255, verbose_name='QR code reference')),
                ('qr_code_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='QR code expires at')),
                ('webhook_received_at', models.DateTimeField(blank=True, null=True, verbose_name='webhook received at')),
                ('webhook_data', models.JSONField(blank=True, default=dict, verbose_name='webhook data')),
                ('error_code', models.CharField(blank=True, max_length=50, verbose_name='error code')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('retry_count', models.IntegerField(default=0, verbose_name='retry count')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_money_transaction', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'mobile money transaction',
                'verbose_name_plural': 'mobile money transactions',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='OrangeMoneyPaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orange_transaction_id', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Orange transaction ID')),
                ('payment_token', models.CharField(blank=True, max_length=255, verbose_name='payment token')),
                ('otp_required', models.BooleanField(default=False, verbose_name='OTP required')),
                ('otp_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='OTP sent at')),
                ('notify_url', models.URLField(blank=True, verbose_name='notify URL')),
                ('is_paid', models.BooleanField(default=False, verbose_name='is paid')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mobile_money_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orange_money_request', to='payments.mobilemoneytransaction')),
            ],
            options={
                'verbose_name': 'Orange Money payment request',
                'verbose_name_plural': 'Orange Money payment requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50, verbose_name='provider')),
                ('event_type', models.CharField(max_length=100, verbose_name='event type')),
                ('payload', models.JSONField(verbose_name='payload')),
                ('headers', models.JSONField(default=dict, verbose_name='headers')),
                ('is_processed', models.BooleanField(default=False, verbose_name='is processed')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('processing_error', models.TextField(blank=True, verbose_name='processing error')),
                ('retry_count', models.IntegerField(default=0, verbose_name='retry count')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mobile_money_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to='payments.mobilemoneytransaction')),
            ],
            options={
                'verbose_name': 'payment webhook',
                'verbose_name_plural': 'payment webhooks',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='WavePaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wave_transaction_id', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Wave transaction ID')),
                ('wave_checkout_id', models.CharField(blank=True, max_length=255, verbose_name='Wave checkout ID')),
                ('qr_code_data', models.TextField(blank=True, verbose_name='QR code data')),
                ('qr_code_url', models.URLField(blank=True, verbose_name='QR code URL')),
                ('payment_url', models.URLField(blank=True, verbose_name='payment URL')),
                ('webhook_signature', models.CharField(blank=True, max_length=255, verbose_name='webhook signature')),
                ('is_paid', models.BooleanField(default=False, verbose_name='is paid')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mobile_money_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wave_request', to='payments.mobilemoneytransaction')),
            ],
            options={
                'verbose_name': 'Wave payment request',
                'verbose_name_plural': 'Wave payment requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mobilemoneytransaction',
            index=models.Index(fields=['-initiated_at'], name='payments_mo_initiat_5fc83a_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilemoneytransaction',
            index=models.Index(fields=['provider', '-initiated_at'], name='payments_mo_provide_a84f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilemoneytransaction',
            index=models.Index(fields=['status'], name='payments_mo_status_e1f7d0_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilemoneytransaction',
            index=models.Index(fields=['provider_transaction_id'], name='payments_mo_provide_6e910c_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilemoneytransaction',
            index=models.Index(fields=['qr_code_reference'], name='payments_mo_qr_code_5156e8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['-received_at'], name='payments_pa_receive_af2fe6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['provider', '-received_at'], name='payments_pa_provide_24a90c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['is_processed'], name='payments_pa_is_proc_285827_idx'),
        ),
    ]
