# Generated by Django 5.0.1 on 2026-02-17 03:07

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_currency', models.CharField(max_length=3, verbose_name='base currency')),
                ('quote_currency', models.CharField(max_length=3, verbose_name='quote currency')),
                ('rate', models.DecimalField(decimal_places=6, help_text='How much of quote_currency equals 1 unit of base_currency', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='exchange rate')),
                ('buy_rate', models.DecimalField(decimal_places=6, help_text='Rate at which we buy base_currency', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='buy rate')),
                ('sell_rate', models.DecimalField(decimal_places=6, help_text='Rate at which we sell base_currency', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='sell rate')),
                ('source', models.CharField(default='API', help_text='Source of exchange rate (API, Manual, etc.)', max_length=50, verbose_name='source')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('effective_from', models.DateTimeField(auto_now_add=True, verbose_name='effective from')),
                ('effective_to', models.DateTimeField(blank=True, null=True, verbose_name='effective to')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'exchange rate',
                'verbose_name_plural': 'exchange rates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['base_currency', 'quote_currency', '-created_at'], name='exchange_ex_base_cu_fce0af_idx'), models.Index(fields=['is_active'], name='exchange_ex_is_acti_70d1b2_idx')],
                'unique_together': {('base_currency', 'quote_currency', 'effective_from')},
            },
        ),
        migrations.CreateModel(
            name='CurrencyConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_currency', models.CharField(max_length=3, verbose_name='from currency')),
                ('to_currency', models.CharField(max_length=3, verbose_name='to currency')),
                ('from_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='from amount')),
                ('to_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='to amount')),
                ('rate_applied', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='rate applied')),
                ('converted_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='currency_conversion', to='transactions.transaction')),
                ('exchange_rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='exchange.exchangerate')),
            ],
            options={
                'verbose_name': 'currency conversion',
                'verbose_name_plural': 'currency conversions',
                'ordering': ['-converted_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_currency', models.CharField(max_length=3, verbose_name='base currency')),
                ('quote_currency', models.CharField(max_length=3, verbose_name='quote currency')),
                ('open_rate', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='open rate')),
                ('high_rate', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='high rate')),
                ('low_rate', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='low rate')),
                ('close_rate', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='close rate')),
                ('date', models.DateField(verbose_name='date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'exchange rate history',
                'verbose_name_plural': 'exchange rate histories',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['base_currency', 'quote_currency', '-date'], name='exchange_ex_base_cu_e03841_idx')],
                'unique_together': {('base_currency', 'quote_currency', 'date')},
            },
        ),
    ]
