# Generated by Django 5.0.1 on 2026-02-17 03:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='phone number')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('nationality', models.CharField(blank=True, max_length=3, verbose_name='nationality')),
                ('country_of_residence', models.CharField(blank=True, max_length=3, verbose_name='country of residence')),
                ('address_line1', models.CharField(blank=True, max_length=255, verbose_name='address line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='address line 2')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='postal code')),
                ('kyc_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ADDITIONAL_INFO_REQUIRED', 'Additional Information Required')], default='NOT_STARTED', max_length=30, verbose_name='KYC status')),
                ('kyc_level', models.IntegerField(default=0, help_text='0: No KYC, 1: Basic KYC, 2: Full KYC', verbose_name='KYC level')),
                ('kyc_submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='KYC submitted at')),
                ('kyc_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='KYC approved at')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='email verified')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='phone verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('ID_CARD', 'ID Card'), ('PASSPORT', 'Passport'), ('DRIVERS_LICENSE', "Driver's License"), ('RESIDENCE_PERMIT', 'Residence Permit'), ('PROOF_OF_ADDRESS', 'Proof of Address'), ('SELFIE', 'Selfie')], max_length=50, verbose_name='document type')),
                ('document_file', models.FileField(upload_to='kyc_documents/', verbose_name='document file')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='document number')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='status')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC document',
                'verbose_name_plural': 'KYC documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(max_length=50, verbose_name='activity type')),
                ('description', models.TextField(verbose_name='description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user activity log',
                'verbose_name_plural': 'user activity logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='accounts_us_created_643629_idx'), models.Index(fields=['user', '-created_at'], name='accounts_us_user_id_3c3f09_idx')],
            },
        ),
    ]
