# Generated by Django 5.0.1 on 2026-02-17 03:07

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_type', models.CharField(choices=[('SEPA_INSTANT', 'SEPA Instant'), ('SEPA_STANDARD', 'SEPA Standard')], default='SEPA_INSTANT', max_length=20, verbose_name='transfer type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='currency')),
                ('beneficiary_name', models.CharField(max_length=255, verbose_name='beneficiary name')),
                ('beneficiary_iban', models.CharField(max_length=34, verbose_name='beneficiary IBAN')),
                ('beneficiary_bic', models.CharField(blank=True, max_length=11, verbose_name='beneficiary BIC')),
                ('reference', models.CharField(blank=True, max_length=140, verbose_name='reference')),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], default='INITIATED', max_length=20, verbose_name='status')),
                ('payment_provider', models.CharField(default='STRIPE', max_length=50, verbose_name='payment provider')),
                ('provider_transfer_id', models.CharField(blank=True, max_length=255, unique=True, verbose_name='provider transfer ID')),
                ('provider_metadata', models.JSONField(blank=True, default=dict, verbose_name='provider metadata')),
                ('expected_arrival_date', models.DateTimeField(blank=True, null=True, verbose_name='expected arrival date')),
                ('actual_arrival_date', models.DateTimeField(blank=True, null=True, verbose_name='actual arrival date')),
                ('error_code', models.CharField(blank=True, max_length=50, verbose_name='error code')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('failure_reason', models.TextField(blank=True, verbose_name='failure reason')),
                ('retry_count', models.IntegerField(default=0, verbose_name='retry count')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='wallets.bankaccount')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfer', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'bank transfer',
                'verbose_name_plural': 'bank transfers',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransferReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_reason_code', models.CharField(choices=[('ACCOUNT_CLOSED', 'Account Closed'), ('NO_ACCOUNT', 'No Account'), ('INVALID_ACCOUNT_NUMBER', 'Invalid Account Number'), ('INSUFFICIENT_FUNDS', 'Insufficient Funds'), ('BANK_PROCESSING_ERROR', 'Bank Processing Error'), ('BENEFICIARY_DECEASED', 'Beneficiary Deceased'), ('OTHER', 'Other Reason')], max_length=50, verbose_name='return reason code')),
                ('return_reason_description', models.TextField(verbose_name='return reason description')),
                ('return_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='return amount')),
                ('bank_return_reference', models.CharField(blank=True, max_length=255, verbose_name='bank return reference')),
                ('is_refunded', models.BooleanField(default=False, verbose_name='is refunded')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='refunded at')),
                ('returned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_transfer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_details', to='banking.banktransfer')),
            ],
            options={
                'verbose_name': 'bank transfer return',
                'verbose_name_plural': 'bank transfer returns',
                'ordering': ['-returned_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransferWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50, verbose_name='provider')),
                ('event_type', models.CharField(max_length=100, verbose_name='event type')),
                ('event_id', models.CharField(blank=True, max_length=255, unique=True, verbose_name='event ID')),
                ('payload', models.JSONField(verbose_name='payload')),
                ('headers', models.JSONField(default=dict, verbose_name='headers')),
                ('signature', models.CharField(blank=True, max_length=255, verbose_name='signature')),
                ('is_verified', models.BooleanField(default=False, verbose_name='is verified')),
                ('is_processed', models.BooleanField(default=False, verbose_name='is processed')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('processing_error', models.TextField(blank=True, verbose_name='processing error')),
                ('retry_count', models.IntegerField(default=0, verbose_name='retry count')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to='banking.banktransfer')),
            ],
            options={
                'verbose_name': 'bank transfer webhook',
                'verbose_name_plural': 'bank transfer webhooks',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='StripeTransferDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_payout_id', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Stripe payout ID')),
                ('stripe_balance_transaction_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe balance transaction ID')),
                ('stripe_bank_account_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe bank account ID')),
                ('stripe_connected_account_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe connected account ID')),
                ('stripe_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Stripe fee')),
                ('stripe_status', models.CharField(blank=True, max_length=50, verbose_name='Stripe status')),
                ('stripe_arrival_date', models.DateField(blank=True, null=True, verbose_name='Stripe arrival date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_transfer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_details', to='banking.banktransfer')),
            ],
            options={
                'verbose_name': 'Stripe transfer details',
                'verbose_name_plural': 'Stripe transfer details',
            },
        ),
        migrations.AddIndex(
            model_name='banktransfer',
            index=models.Index(fields=['-initiated_at'], name='banking_ban_initiat_add2cb_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransfer',
            index=models.Index(fields=['status'], name='banking_ban_status_2bc442_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransfer',
            index=models.Index(fields=['provider_transfer_id'], name='banking_ban_provide_7b019f_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransfer',
            index=models.Index(fields=['bank_account', '-initiated_at'], name='banking_ban_bank_ac_46d8b8_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransferwebhook',
            index=models.Index(fields=['-received_at'], name='banking_ban_receive_0842a0_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransferwebhook',
            index=models.Index(fields=['provider', '-received_at'], name='banking_ban_provide_667507_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransferwebhook',
            index=models.Index(fields=['is_processed'], name='banking_ban_is_proc_d9eadf_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransferwebhook',
            index=models.Index(fields=['event_id'], name='banking_ban_event_i_081be2_idx'),
        ),
    ]
