# Generated by Django 5.0.1 on 2026-02-17 03:07

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=50, verbose_name='transaction type')),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='fixed fee')),
                ('percentage_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage (e.g., 1.5 for 1.5%)', max_digits=5, verbose_name='percentage fee')),
                ('min_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='minimum fee')),
                ('max_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='maximum fee')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='currency')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'transaction fee',
                'verbose_name_plural': 'transaction fees',
                'ordering': ['transaction_type'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kyc_level', models.IntegerField(unique=True, verbose_name='KYC level')),
                ('daily_receive_limit', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='daily receive limit')),
                ('daily_send_limit', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='daily send limit')),
                ('min_transaction_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='minimum transaction amount')),
                ('max_transaction_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='maximum transaction amount')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='currency')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'transaction limit',
                'verbose_name_plural': 'transaction limits',
                'ordering': ['kyc_level'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('RECEIVE_MOBILE_MONEY', 'Receive from Mobile Money'), ('SEND_BANK_TRANSFER', 'Send to Bank Account'), ('WALLET_TO_WALLET', 'Wallet to Wallet'), ('FEE', 'Transaction Fee'), ('REFUND', 'Refund')], max_length=50, verbose_name='transaction type')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20, verbose_name='status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount')),
                ('currency', models.CharField(max_length=3, verbose_name='currency')),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='original amount')),
                ('original_currency', models.CharField(blank=True, max_length=3, verbose_name='original currency')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='exchange rate')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='fee amount')),
                ('fee_currency', models.CharField(default='EUR', max_length=3, verbose_name='fee currency')),
                ('external_transaction_id', models.CharField(blank=True, help_text='Transaction ID from payment provider (Wave, Stripe, etc.)', max_length=255, verbose_name='external transaction ID')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('error_code', models.CharField(blank=True, max_length=50, verbose_name='error code')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transactions', to='wallets.wallet')),
                ('source_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transactions', to='wallets.wallet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10, verbose_name='entry type')),
                ('account_type', models.CharField(choices=[('USER_WALLET', 'User Wallet'), ('REVENUE', 'Revenue'), ('FEES', 'Fees'), ('PENDING', 'Pending'), ('LOCKED', 'Locked'), ('FLOAT', 'Float Account')], max_length=20, verbose_name='account type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='amount')),
                ('currency', models.CharField(max_length=3, verbose_name='currency')),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='balance after')),
                ('description', models.TextField(verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='wallets.wallet')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'ledger entry',
                'verbose_name_plural': 'ledger entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-initiated_at'], name='transaction_initiat_542dbb_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-initiated_at'], name='transaction_user_id_109b07_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='transaction_status_71abbb_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['external_transaction_id'], name='transaction_externa_04b8ee_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['-created_at'], name='transaction_created_fc863a_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['wallet', '-created_at'], name='transaction_wallet__0979a2_idx'),
        ),
    ]
