# Generated by Django 5.0.1 on 2026-02-17 03:07

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=255, verbose_name='bank name')),
                ('account_holder_name', models.CharField(max_length=255, verbose_name='account holder name')),
                ('iban', models.CharField(max_length=34, unique=True, verbose_name='IBAN')),
                ('bic_swift', models.CharField(blank=True, max_length=11, verbose_name='BIC/SWIFT')),
                ('account_type', models.CharField(choices=[('CHECKING', 'Checking Account'), ('SAVINGS', 'Savings Account')], default='CHECKING', max_length=20, verbose_name='account type')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_default', models.BooleanField(default=False, verbose_name='default account')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bank account',
                'verbose_name_plural': 'bank accounts',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileMoneyAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money'), ('MTN_MOMO', 'MTN Mobile Money'), ('MOOV_MONEY', 'Moov Money'), ('FREE_MONEY', 'Free Money')], max_length=50, verbose_name='provider')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone number')),
                ('account_name', models.CharField(max_length=255, verbose_name='account name')),
                ('country', models.CharField(max_length=3, verbose_name='country')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_money_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mobile money account',
                'verbose_name_plural': 'mobile money accounts',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'provider', 'phone_number')},
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('XOF', 'West African CFA Franc'), ('XAF', 'Central African CFA Franc'), ('GHS', 'Ghanaian Cedi'), ('NGN', 'Nigerian Naira'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('UGX', 'Ugandan Shilling'), ('ZAR', 'South African Rand')], max_length=3, verbose_name='currency')),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='available balance')),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance pending confirmation', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='pending balance')),
                ('locked_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance locked for processing transactions', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='locked balance')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wallet',
                'verbose_name_plural': 'wallets',
                'ordering': ['currency'],
                'unique_together': {('user', 'currency')},
            },
        ),
    ]
